### ISSUE TITLE
Where is 'question:index' in the book?

### ISSUE THREAD

**Issue by MUDASSARHASHMI** [tomaratyn/Answerly#1]
Did you ever even replicated book's code to see what's the difference? At least have the shared repository upto date with code.

**Comment by tomaratyn** [comment]
Both `questions:index` and `qanda:index` refer to the same view. There is no `question:index` in the book, or in the code, that I noticed. However, it might be that there's a typo that I missed and accidentally wrote `question` instead of `questions`.
